from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Proyecto Computadores.com
    Package: TestProject.Generated.Tests.ProyectoComputadorescom
    Test: CP-03.2
    Generated by: Andres Diaz (diazandresfelipe91@gmail.com)
    Generated on 09/20/2022, 19:52:52
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="6vg3AYBdNyUgmB8Dn2JI8usHfm5RJkaE6bkMe7kVMXI",
                              project_name="Proyecto Computadores.com",
                              job_name="CP-03.2")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Se busca comprobar que el usuario no sea capaz de añadir más productos al carrito de los que hay disponibles."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost/wordpress/"
    Correo = ""
    Password = ""
    Cantidad = ""

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Salir'
    salir = driver.find_element(By.XPATH,
                                "//li[5]/a[. = 'Salir']")
    salir.click()

    # 3. Click 'Cuenta'
    cuenta = driver.find_element(By.XPATH,
                                 "//li[3]/a[. = 'Cuenta']")
    cuenta.click()

    # 4. Type '{Correo}' in 'username-13'
    username_13 = driver.find_element(By.CSS_SELECTOR,
                                      "#username-13")
    username_13.send_keys(f'{Correo}')

    # 5. Type '{Password}' in 'user_password-13'
    user_password_13 = driver.find_element(By.CSS_SELECTOR,
                                           "#user_password-13")
    user_password_13.send_keys(f'{Password}')

    # 6. Click 'um-submit-btn'
    um_submit_btn = driver.find_element(By.CSS_SELECTOR,
                                        "#um-submit-btn")
    um_submit_btn.click()

    # 7. Click 'Tienda'
    tienda = driver.find_element(By.XPATH,
                                 "//li[2]/a[. = 'Tienda']")
    tienda.click()

    # 8. Click 'IMG'
    img = driver.find_element(By.XPATH,
                              "//li[4]//img")
    img.click()

    # 9. Clear 'quantity' contents
    quantity = driver.find_element(By.CSS_SELECTOR,
                                   "#quantity_6329e0725535f")
    quantity.clear()

    # 10. Type '{Cantidad}' in 'quantity'
    quantity = driver.find_element(By.CSS_SELECTOR,
                                   "#quantity_6329e0725535f")
    quantity.send_keys(f'{Cantidad}')

    # 11. Click 'add-to-cart'
    add_to_cart = driver.find_element(By.CSS_SELECTOR,
                                      "[name='add-to-cart']")
    add_to_cart.click()

    # 12. Click 'Disponibilidad:'
    disponibilidad_colon_ = driver.find_element(By.XPATH,
                                                "//span[. = 'Disponibilidad:']")
    disponibilidad_colon_.click()

    # 13. Click 'Salir'
    salir = driver.find_element(By.XPATH,
                                "//li[5]/a[. = 'Salir']")
    salir.click()
