from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Proyecto Computadores.com
    Package: TestProject.Generated.Tests.ProyectoComputadorescom
    Test: CP-05.2
    Generated by: Andres Diaz (diazandresfelipe91@gmail.com)
    Generated on 09/20/2022, 19:53:51
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="6vg3AYBdNyUgmB8Dn2JI8usHfm5RJkaE6bkMe7kVMXI",
                              project_name="Proyecto Computadores.com",
                              job_name="CP-05.2")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Se busca comprobar que el usuario no pueda colocar una reseña en algún producto, en donde esta no contenga la calificación del producto."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost/wordpress/"
    Correo = ""
    Password = ""

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'Salir'
    salir = driver.find_element(By.XPATH,
                                "//li[5]/a[. = 'Salir']")
    salir.click()

    # 3. Click 'Cuenta'
    cuenta = driver.find_element(By.XPATH,
                                 "//li[3]/a[. = 'Cuenta']")
    cuenta.click()

    # 4. Type '{Correo}' in 'username-13'
    username_13 = driver.find_element(By.CSS_SELECTOR,
                                      "#username-13")
    username_13.send_keys(f'{Correo}')

    # 5. Type '{Password}' in 'user_password-13'
    user_password_13 = driver.find_element(By.CSS_SELECTOR,
                                           "#user_password-13")
    user_password_13.send_keys(f'{Password}')

    # 6. Click 'um-submit-btn'
    um_submit_btn = driver.find_element(By.CSS_SELECTOR,
                                        "#um-submit-btn")
    um_submit_btn.click()

    # 7. Click 'Tienda'
    tienda = driver.find_element(By.XPATH,
                                 "//li[2]/a[. = 'Tienda']")
    tienda.click()

    # 8. Click 'IMG'
    img = driver.find_element(By.XPATH,
                              "//li[4]//img")
    img.click()

    # 9. Scroll window by ('0','832')
    driver.execute_script("window.scrollBy(0,832)")

    # 10. Click 'Valoraciones (0)'
    valoraciones_0_ = driver.find_element(By.XPATH,
                                          "//a[. = '\n\t\t\t\t\t\tValoraciones (0)\t\t\t\t\t']")
    valoraciones_0_.click()

    # 11. Click 'submit'
    submit = driver.find_element(By.CSS_SELECTOR,
                                 "#submit")
    submit.click()

    # 12. Click 'No hay valoraciones aún.'
    no_hay_valoraciones_a_n_ = driver.find_element(By.XPATH,
                                                   "//p[. = 'No hay valoraciones aún.']")
    no_hay_valoraciones_a_n_.click()
